### ISSUE TITLE
Symbols are outdated

### ISSUE THREAD

**Issue by frspp** [fmidev/opendata-resources#9]
Symbols are outdated in folder https://github.com/fmidev/opendata-resources/tree/master/symbols

See
https://www.ilmatieteenlaitos.fi/ajankohtaista/493317979
https://www.ilmatieteenlaitos.fi/saamerkkien-selitykset

**Comment by sirviot** [comment]
The issue should be fixed with pull request: INSPIRE-981: Open SmartSymbol icon sets #10

**Comment by sirviot** [comment]
Thank you for reporting this @frspp.
